board_service/board_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board_service/catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import CatalogConfig
from .views import IndexTemplateView, feedback, ProductListView, FeedBackListView, ProductDetailView, ProductCreateView, \
    ProductUpdateView, ProductDeleteView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView, BlogCreateView, \
    BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, PublishProductView, ModerateProductList

app_name = CatalogConfig.name

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('feedback/', feedback, name='feedback'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('about/', FeedBackListView.as_view(), name='about_list'),
    path('products/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('add_product/', ProductCreateView.as_view(), name='add_product'),
    path('update_product/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete_product/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('add_category/', CategoryCreateView.as_view(), name='add_category'),
    path('update_category/<int:pk>/', CategoryUpdateView.as_view(), name='update_category'),
    path('delete_category/<int:pk>/', CategoryDeleteView.as_view(), name='delete_category'),
    path('add_blog/', BlogCreateView.as_view(), name='add_blog'),
    path('blogs/', BlogListView.as_view(), name='blog_list'),
    path('blogs/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update_blog/<int:pk>/', BlogUpdateView.as_view(), name='update_blog'),
    path('delete_blog/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),
    path('publish_product/<int:pk>/', PublishProductView.as_view(), name='publish_product'),
    path('moderate_products/', ModerateProductList.as_view(), name='moderate_products')
]

board_service/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, UserRegisterView, UserProfileView, verify_registration, user_reset_password, \
    PasswordChangeView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('<int:user_pk>/<slug:user_identity>/', verify_registration, name='verify_registration'),
    path('reset_password/', user_reset_password, name='reset_password'),
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/change_password_done.html'),
         name='password_change_done')
]

board_service/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


# Create your models here.
class User(AbstractUser):
    username = None
    phone = models.CharField(max_length=30, verbose_name='номер телефона', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=150, verbose_name='страна', **NULLABLE)
    email = models.EmailField(unique=True, verbose_name='email')
    user_identity = models.CharField(max_length=20, verbose_name='ключ', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

board_service/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, PasswordChangeForm

from catalog.forms import StyleFormMixin
from users.models import User


class LoginForm(StyleFormMixin, AuthenticationForm):
    class Meta:
        model = User
        fields = ('email', 'password')


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar', 'password', 'country', 'phone',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class UserChangePasswordForm(StyleFormMixin, PasswordChangeForm):
    class Meta:
        model = User

board_service/users/views.py
import random
import string

from django.conf import settings
from django.contrib.auth.views import LoginView as BaseLoginView, PasswordChangeView as BasePasswordChangeView
from django.core.mail import send_mail
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.forms import LoginForm, UserRegisterForm, UserProfileForm, UserChangePasswordForm
from users.models import User


# Create your views here.
class LoginView(BaseLoginView):
    """Класс контроллер для авторизации пользователей."""
    template_name = 'users/login.html'
    form_class = LoginForm


class UserRegisterView(CreateView):
    """Класс контроллер для регистрации пользователей."""
    model = User
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('catalog:index')

    def form_valid(self, form):
        """Метод позволяет активировать только тех пользователей, которые прошли верификацию через email."""

        if form.is_valid():
            # Отключение пользователя
            self.object = form.save(commit=False)
            self.object.is_active = False

            # Генерирование ключа
            user_key = ''.join(random.choice(string.digits + string.ascii_lowercase) for _ in range(20))
            self.object.user_identity = user_key
            self.object = form.save()

            # Отправка email
            send_mail(
                subject='Подтвержение регистрации на портале <Catalogue>.',
                message=f'Здравстуйте, {self.object.email}!\n Для завершения регистрации, пожалуйста, перейдите по'
                        f' ссылкe:\n\nhttp://127.0.0.1:8000/users/{self.object.pk}/{user_key}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.object.email, ]
            )

            return render(self.request, 'users/verify_registration.html')

        return super().form_valid(form)

    def get_object(self, queryset=None):
        """Метод возвращает текущего пользователя."""
        return self.request.user

    def get_context_data(self, **kwargs):
        """Метод добавляет в контекст шаблонную переменную user с текущем пользователем."""
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


def verify_registration(request, user_pk, user_identity):
    """Функция контроллер активирует пользователя на сайте, если тот прошел верификацию. Для этого генерируется HTML-страница
    verify_registration.html, которая сообщает пользователю, что на указанную электронную почту отправляет инструкцию
    для верификации.
    """

    # Получени пользователя по pk
    user = User.objects.get(pk=user_pk)
    context = {
        'user': user
    }

    # Если переданный ключ совпадает с ключом пользователя в бд, то пользователь активируется на сайте.
    if user.user_identity == user_identity:
        user.is_active = True
        user.save()

    return render(request, 'users/verify_registration.html', context)


class UserProfileView(UpdateView):
    """Класс контроллер для изменения данных текущего пользователя."""
    success_url = reverse_lazy('catalog:index')
    form_class = UserProfileForm
    model = User

    def get_object(self, queryset=None):
        """Метод возвращает текущего пользователя."""
        return self.request.user


def user_reset_password(request):
    """Функция контроллер сбрасывает пароль по указанному email и генерирует новый. Новый пароль присылается
    пользователю по указанному email."""

    template_name = 'users/reset_password.html'

    if request.method == 'POST':
        # Получение email из POST-запроса
        user_email = request.POST.get('email')

        # Поиск указанного email в бд и запись результата в контекст
        user_exists = User.objects.filter(email=f'{user_email}').exists()
        context = {
            'user': user_exists
        }

        # Если указанный пользователь есть в бд, то его пароль сбрасывается генерируется новый. Новый пароль присылается
        # пользователю по указанному email.
        if user_exists:
            # Генерация пароля и присвоение его пользователю
            new_password = ''.join(random.choice(string.digits + string.ascii_lowercase) for _ in range(12))
            user = User.objects.get(email=f'{user_email}')
            user.set_password(new_password)
            user.save()

            # Отправка email пользователю с новым паролем
            send_mail(
                subject='Cброс пароля на портале <Catalogue>.',
                message=f'Здравстуйте!\n\nС вашей учетной записи поступил запрос на отправку нового пароля\n\n\n\n.'
                        f'Ваш новый пароль: {new_password}\nЕсли это не Ваш запрос, не беспокойтесь.'
                        f'Это сообщение видно только вам.'
                        f'Если это ошибка, просто войдите на сайт с Вашим новым паролем и затем измените его согласно '
                        f'вашим предпочтениям.\n\n\nС уважением, администрация портала <Catalogue>.',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[user_email, ]
            )
            return render(request, 'users/reset_password_done.html', context)

        return render(request, template_name, context)

    return render(request, 'users/reset_password.html')


class PasswordChangeView(BasePasswordChangeView):
    """Класс контроллер для изменения пароля авторизованного на сайте пользователя."""

    model = User
    form_class = UserChangePasswordForm
    template_name = 'users/change_password.html'
    success_url = reverse_lazy('users:password_change_done')

board_service/users/templates/users/change_password.html
{% extends 'layout/basic.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="card mt-5 mb-5">
                <div class="card-header">
                    <h4>Изменение пароля</h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Изменить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board_service/users/templates/users/change_password_done.html
{% extends 'layout/basic.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="card mt-5 mb-5">
                <div class="card-header">
                    <h4>Ваш пароль успешно изменен</h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>{{ title }}</p>
                        <a href="{% url 'catalog:index' %}" class="btn btn-primary">На главную страницу</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board_service/users/templates/users/login.html
{% extends 'layout/basic.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="card mt-5 mb-5">
                <div class="card-header">
                    <h4>Вход </h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Войти</button>
                        <a href="{% url 'users:reset_password' %}" class="btn btn-secondary">Забыли пароль?</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board_service/users/templates/users/register.html
{% extends 'layout/basic.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="card mt-5 mb-5">
                <div class="card-header">
                    <h4>Регистрация </h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Создать</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board_service/users/templates/users/reset_password.html
{% extends 'layout/basic.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="card mt-5 mb-5">
                <div class="card-header">
                    <h4>Сброс пароля</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Пожалуйста, введите действующую электронную почту для отправки сгенерированного пароля</p>
                        <label for="basic-addon1" class="form-label">Электронная почта</label>
                        <div class="input mb-3">
                            <input type="email" class="form-control" aria-describedby="basic-addon1"
                                   id="basic-addon1" name="email" placeholder="Email...">
                        </div>
                        {% if user %}
                        {% else %}
                            <p class="text-danger">Такого пользователя не существует</p>
                        {% endif %}
                        <button type="submit" class="btn btn-danger">Отправить</button>
                        <a href="{% url 'catalog:index' %}" class="btn btn-primary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board_service/users/templates/users/reset_password_done.html
{% extends 'layout/basic.html' %}

{% block content %}
<div class="container-fluid" xmlns="http://www.w3.org/1999/html">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="card mt-5 mb-5">
                <div class="card-header">
                    <h4>Сброс пароля</h4>
                </div>
                <div class="card-body">
                    <p>
                        Здравствуйте!<br> Пароль для вашей учетной записи был сброшен, пожалуйста, проверьте вашу
                        электронную почту, куда был выслан новый пароль. <br><br> C уважением, администрация сайта!
                    </p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'catalog:index' %}" class="btn btn-primary">На главную страницу</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board_service/users/templates/users/user_form.html
{% extends 'layout/basic.html' %}
{% load products_tags %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <div class="card mt-5 mb-5">
                <div class="card-header">
                    <h4>Изменение информации о пользователе</h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Изменить</button>
                        <a href="{% url 'users:password_change' %}" class="btn btn-danger"> Изменить пароль</a>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card mt-5 mb-5">
                <div class="card-header">
                    <h4 class="text-center">Текущая информация о пользователе</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="text-center">
                                <img src="{{ user.avatar|media_path }}" class="img-fluid">
                            </div>
                        </div>
                        <div class="col-md-9">
                            <ul>
                                <li>
                                    <strong>Электронная почта: </strong>{{ user.email }}
                                </li>
                                <li>
                                    <strong>Имя: </strong>{{ user.first_name }}
                                </li>
                                <li>
                                    <strong>Фамилие: </strong>{{ user.last_name }}
                                </li>
                                <li>
                                    <strong>Номер телефона: </strong>{{ user.phone }}
                                </li>
                                <li>
                                    <strong>Страна проживания: </strong>{{ user.country }}
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board_service/users/templates/users/verify_registration.html
{% extends 'layout/basic.html' %}

{% block content %}
<div class="container-fluid" xmlns="http://www.w3.org/1999/html">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="card mt-5 mb-5">
                <div class="card-header">
                    <h4>Подтверждение регистрации</h4>
                </div>
                <div class="card-body">
                    {% if user.is_active %}
                    <p>
                        Уважаемый {{ user.email }}! <br> Спасибо за регистрацию!
                    </p>
                    {% else %}
                    <p>
                        Здравствуйте, уважаемый пользователь! <br> Спасибо, что вы с нами! Для завершения регистрации на
                        нашем портале, пожалуйста, подтвердите вашу электронную почту. Письмо с дальнейшими инструкциями
                        отправлено на ваш почтовый ящик. <br> С уважением, администрация портала!
                    </p>
                    {% endif %}
                </div>
                <div class="card-footer">
                    <a href="{% url 'catalog:index' %}" class="btn btn-primary">На главную страницу</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}