board_service/board_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board_service/catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import CatalogConfig
from .views import IndexTemplateView, feedback, ProductListView, FeedBackListView, ProductDetailView, ProductCreateView, \
    ProductUpdateView, ProductDeleteView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView, BlogCreateView, \
    BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, PublishProductView, ModerateProductList

app_name = CatalogConfig.name

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('feedback/', feedback, name='feedback'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('about/', FeedBackListView.as_view(), name='about_list'),
    path('products/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('add_product/', ProductCreateView.as_view(), name='add_product'),
    path('update_product/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete_product/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('add_category/', CategoryCreateView.as_view(), name='add_category'),
    path('update_category/<int:pk>/', CategoryUpdateView.as_view(), name='update_category'),
    path('delete_category/<int:pk>/', CategoryDeleteView.as_view(), name='delete_category'),
    path('add_blog/', BlogCreateView.as_view(), name='add_blog'),
    path('blogs/', BlogListView.as_view(), name='blog_list'),
    path('blogs/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update_blog/<int:pk>/', BlogUpdateView.as_view(), name='update_blog'),
    path('delete_blog/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),
    path('publish_product/<int:pk>/', PublishProductView.as_view(), name='publish_product'),
    path('moderate_products/', ModerateProductList.as_view(), name='moderate_products')
]

board_service/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, UserRegisterView, UserProfileView, verify_registration, user_reset_password, \
    PasswordChangeView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('<int:user_pk>/<slug:user_identity>/', verify_registration, name='verify_registration'),
    path('reset_password/', user_reset_password, name='reset_password'),
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/change_password_done.html'),
         name='password_change_done')
]

board_service/catalog/models.py
from decimal import Decimal

from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


# Create your models here.
class Product(models.Model):
    """
    Модель Product для сохранения определенного товара в базе данных. Поля:
    1) name — название товара, 2) description — описание товара, 3) image — иконка товара, 4) published — дата
    публикации, 5) changed — дата изменения, 6) price — цена, 7) category — категория, ссылающаяся на поле модели
    Category.
    """
    name = models.CharField(max_length=50, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    image = models.ImageField(upload_to='products/', **NULLABLE, verbose_name='Изображение')
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')
    changed = models.DateTimeField(auto_now=True, db_index=True, verbose_name='Изменения')
    price = models.FloatField(verbose_name='Цена')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='categories',
                                 verbose_name='Категория', )
    user_product = models.ForeignKey('users.User', on_delete=models.SET_NULL, verbose_name='пользователь',
                                     **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('-published',)
        permissions = [
            (
                'set_published',
                'Can publish Продукт'
            )
        ]


class Category(models.Model):
    """
    Модель Category для сохранения категорий товаров в базе данных. Поля:
    1) category — название категории, 2) description — описание категории.
    """
    category = models.CharField(max_length=50, verbose_name='Категория')
    description = models.TextField(verbose_name='Описание')
    user_category = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                                      verbose_name='пользователь')

    def __str__(self):
        return f'{self.category}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('category',)


class Feedback(models.Model):
    """
    Модель Feedback для обратной связи от пользователей в базе данных. Поля:
    1) first_name — имя пользователя, 2) last_name — фамилия пользователя, 3) email — электронная почта пользователя,
    4) phone — номер телефона пользователя, 5) country — страна, откуда пользователь, 6) message — сообщение от
    пользователя, 7) publish — дата публикации.
    """
    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    email = models.EmailField(max_length=100, verbose_name='Электронная почта')
    phone = models.CharField(max_length=30, verbose_name='Номер телефона', **NULLABLE)

    # Страна выбирается из выпадающего списка
    class Kinds(models.TextChoices):
        RUSSIA = 'Россия', 'Россия'
        AZERBAIJAN = 'Азербайджан', 'Азербайджан'
        ARMENIA = 'Армения', 'Армения'
        BELARUS = 'Белоруссия', 'Белоруссия'
        KAZAKHSTAN = 'Казахстан', 'Казахстан'
        KYRGYZSTAN = 'Киргизия', 'Киргизия'
        MOLDAVIA = 'Молдавия', 'Молдавия'
        TAJIKISTAN = 'Таджикистан', 'Таджикистан'
        UZBEKISTAN = 'Узбекистан', 'Узбекистан'

    country = models.CharField(max_length=150, choices=Kinds.choices, default=Kinds.RUSSIA, verbose_name='Страна')
    message = models.TextField(verbose_name='Сообщение')
    publish = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')

    class Meta:
        verbose_name = 'Обратная связь'
        verbose_name_plural = 'Обратные связи'
        ordering = ('-publish',)


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    slug = models.CharField(max_length=50, **NULLABLE, verbose_name='slug')
    view_count = models.IntegerField(default=0, verbose_name='Просмотры')
    content = models.TextField(**NULLABLE, verbose_name='Содержимое')
    image = models.ImageField(upload_to='blogs/', **NULLABLE, verbose_name='Превью')
    published = models.DateTimeField(db_index=True, auto_now_add=True, verbose_name='Дата создания')
    is_active = models.BooleanField(default=True, verbose_name='Разрешение на публикацию')
    email = models.EmailField(max_length=100, verbose_name='Электронная почта')
    user_blog = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                                  verbose_name='пользователь')

    def __str__(self):
        return f'{self.title}. Просмотров ({self.view_count})'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        ordering = ('-published',)


def increment_version_number():
    max_number = Version.objects.all().order_by('number').last()
    if not max_number:
        return 1.00
    return max_number.number + Decimal('0.1')


class Version(models.Model):
    class VersionName(models.TextChoices):
        NAME_DEVELOP = 'В разработке', 'В разработке'
        NAME_RELEASE = 'Выпуск в производстве', 'Выпуск в производстве'

    title = models.CharField(max_length=150, choices=VersionName.choices, default=VersionName.NAME_DEVELOP,
                             verbose_name='Название')
    number = models.DecimalField(max_digits=3, decimal_places=2, verbose_name='Номер версии',
                                 default=increment_version_number, unique=True)
    is_active = models.BooleanField(default=False, verbose_name='Активность')
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='versions', verbose_name='Продукт')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        ordering = ('-number',)

board_service/catalog/forms.py
import re

from django.forms import models, ValidationError, BaseInlineFormSet

from catalog.models import Product, Category, Blog, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, models.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'image', 'price', 'category')

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        banned_words = r'(.*)(биржа|казино|криптовалюта|крипта|дешево|бесплатно|обман|полиция|радар)(.*)'
        if re.match(banned_words, cleaned_data, flags=re.IGNORECASE):
            raise models.ValidationError('Нельзя публиковать запрещенные товары')

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_published':
                field.widget.attrs['class'] = 'form'
            else:
                field.widget.attrs['class'] = 'form-control'


class CategoryForm(StyleFormMixin, models.ModelForm):
    class Meta:
        model = Category
        fields = ('category', 'description')


class BlogForm(StyleFormMixin, models.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', 'image', 'email')


class VersionForm(models.ModelForm):
    class Meta:
        model = Version
        fields = ('title', 'number', 'is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_active':
                field.widget.attrs['class'] = 'form'
            else:
                field.widget.attrs['class'] = 'form-control'

    def clean_number(self):
        cleaned_data = self.cleaned_data['number']
        if cleaned_data < 1.00:
            raise ValidationError('Номер версии не может быть меньше 1.00')
        return cleaned_data


class VersionBaseInlineFormSet(BaseInlineFormSet):
    def clean(self):
        super().clean()
        active_list = [form.cleaned_data['is_active'] for form in self.forms if 'is_active' in form.cleaned_data]
        if active_list.count(True) > 1:
            raise ValidationError('Возможна лишь одна активная версия. Пожалуйста, активируйте только 1 версию.')


class PublishProductForm(models.ModelForm):
    class Meta:
        model = Product
        fields = ('is_published',)

board_service/catalog/templates/catalog/Blog_detail.html
{% extends "layout/basic.html" %}
{% load products_tags %}
{% load static %}

{% block content %}
<div class="card-header">
    <div class="text-center">
        <h1>{{ object.title|title }}</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="container mt-5">
            <div class="card mt-1 mb-5">
                <div class="row">
                    <div class="col-md-4">
                        <img src="{{ object.image|media_path }}" class="card-img">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ object.title|title }}</h5>
                            <p class="card-text">{{ object.content }}</p>
                            <p class="card-text"><strong>Дата публикации: </strong>{{ object.published }}</p>
                            <p class="card-text"><strong>Количество просмотров: </strong>{{ object.view_count }}</p>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'catalog:update_blog' object.pk %}" class="btn btn-primary">
                        Изменить
                    </a>
                    <a href="{% url 'catalog:delete_blog' object.pk %}" class="btn btn-danger float-right">
                        Удалить
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="container mt-5">
            <div class="card mt-1 mb-5">
                <div class="card-body">
                    <div class="d-grid gap-5 col-6 mx-auto px-auto">
                        <button class="btn btn-info" type="button">Показать контакты</button>
                        <button class="btn btn-success" type="button">Сохранить</button>
                        <a href="{% url 'catalog:feedback' %}" class="btn btn-primary">Обратная связь</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board_service/catalog/templates/catalog/Product_detail.html
{% extends 'layout/basic.html' %}
{% load products_tags %}
{% load static %}

{% block content %}
<div class="card-header">
    <div class="text-center">
        <h1>{{ object.name }}</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="container mt-5">
            <div class="card mt-1 mb-5">
                <div class="row">
                    <div class="col-md-4">
                        <img src="{{ object.image|media_path }}" class="card-img">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    <h5>{{ object.name|title }}</h5>
                                </li>
                                <li class="list-inline-item">
                                    <h5>{{ object.price }} ₽</h5>
                                </li>
                            </ul>
                            <p class="card-text">{{ object.description }}</p>
                            <p><b>Категория:</b> {{ object.category }}</p>
                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    <b>Дата публикации:</b>
                                </li>
                                <li class="list-inline-item">
                                    {{object.published|date:"d.m.Y H:i:s"}}
                                </li>
                                <li class="list-inline-item">
                                    <b>Дата последнего изменения объявления:</b>
                                </li>
                                <li class="list-inline-item">
                                    {{object.changed|date:"d.m.Y H:i:s"}}
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'catalog:update_product' object.pk %}" class="btn btn-primary">
                        Изменить
                    </a>
                    <a href="{% url 'catalog:delete_product' object.pk %}" class="btn btn-danger float-right">
                        Удалить
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="container mt-5">
            <div class="card mt-1 mb-5">
                <div class="card-body">
                    <div class="d-grid gap-5 col-6 mx-auto px-auto">
                        <button class="btn btn-info" type="button">Показать телефон</button>
                        <button class="btn btn-success" type="button">Купить</button>
                        <a href="{% url 'catalog:feedback' %}" class="btn btn-primary">Обратная связь</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board_service/catalog/templates/catalog/blog_list.html
{% extends "layout/basic.html" %}
{% load products_tags %}

{% block content %}
<div class="card-header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-10">
                <div class="text-center">
                    <h4>Блок: повышаем эффективность продаж</h4>
                </div>
            </div>
            {% if user.is_authenticated %}
            <div class="col-md-2">
                <a class="btn btn-primary" href="{% url 'catalog:add_blog' %}">Добавить публикацию</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<div class="card-body">
    <div class="row row-cols-1 row-cols-md-3 g-4 mb-5">
        {% for object in page_obj %}
        <div class="col">
            <div class="card h-100">
                <div class="card-body">
                    <div class="card-title">
                        <h5 class="text-center">
                            <a href="{% url 'catalog:blog_detail' object.pk %}">{{ object.title|title }}</a>
                            <small>({{ object.slug }})</small>
                        </h5>
                    </div>
                    <img src="{{ object.image|media_path }}" class="card-img">
                    {% if object.content|length <= 100 %}
                    <p class="card-text">{{ object.content }} <a href="{% url 'catalog:blog_detail' object.pk %}">Подробнее</a></p>
                    {% else %}
                    <p class="card-text">{{ object.content|slice:"0:100" }}...<a href="{% url 'catalog:blog_detail' object.pk %}">
                        Подробнее</a>
                    </p>
                    {% endif %}
                    {{ object.user_blog|default:"нет" }}
                </div>
                <div class="card-footer">
                    <p class="text-body-secondary">Опубликовано {{object.published|date:"d.m.Y H:i:s"}}</p>
                    <span> Просмотры: {{ object.view_count }}</span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
        {% include 'catalog/includes/inc_paginate.html' %}
</div>
{% endblock %}

board_service/catalog/templates/catalog/product_detail.html
{% extends 'layout/basic.html' %}
{% load products_tags %}
{% load static %}

{% block content %}
<div class="card-header">
    <div class="text-center">
        <h1>{{ object.name }}</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="container mt-5">
            <div class="card mt-1 mb-5">
                <div class="row">
                    <div class="col-md-4">
                        <img src="{{ object.image|media_path }}" class="card-img">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    <h5>{{ object.name|title }}</h5>
                                </li>
                                <li class="list-inline-item">
                                    <h5>{{ object.price }} ₽</h5>
                                </li>
                            </ul>
                            <p class="card-text">{{ object.description }}</p>
                            <p><b>Категория:</b> {{ object.category }}</p>
                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    <b>Дата публикации:</b>
                                </li>
                                <li class="list-inline-item">
                                    {{object.published|date:"d.m.Y H:i:s"}}
                                </li>
                                <li class="list-inline-item">
                                    <b>Дата последнего изменения объявления:</b>
                                </li>
                                <li class="list-inline-item">
                                    {{object.changed|date:"d.m.Y H:i:s"}}
                                </li>
                            </ul>
                            <p><b>Пользователь:</b> {{ object.user_product|default:"нет" }}</p>
                            <p>
                                {% if perms.catalog.set_published %}
                                <a href="{% url 'catalog:publish_product' object.pk %}" class="btn btn-primary">
                                    Опубликовать
                                </a>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
                {% if user == object.user_product %}
                <div class="card-footer">
                    <a href="{% url 'catalog:update_product' object.pk %}" class="btn btn-primary">
                        Изменить
                    </a>
                    <a href="{% url 'catalog:delete_product' object.pk %}" class="btn btn-danger float-right">
                        Удалить
                    </a>
                </div>
                {% elif user.is_staff %}
                <div class="card-footer">
                    {% if perms.catalog.change_product %}
                    <a href="{% url 'catalog:update_product' object.pk %}" class="btn btn-primary">
                        Изменить
                    </a>
                    {% endif %}
                    {% if perms.catalog.delete_product %}
                    <a href="{% url 'catalog:delete_product' object.pk %}" class="btn btn-danger float-right">
                        Удалить
                    </a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="container mt-5">
            <div class="card mt-1 mb-5">
                <div class="card-body">
                    <div class="d-grid gap-5 col-6 mx-auto px-auto">
                        <button class="btn btn-info" type="button">Показать телефон</button>
                        <button class="btn btn-success" type="button">Купить</button>
                        <a href="{% url 'catalog:feedback' %}" class="btn btn-primary">Обратная связь</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board_service/catalog/templates/catalog/product_list.html
{% extends "layout/basic.html" %}
{% load products_tags %}

{% block content %}
<div class="card-body">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title"><a href="{% url 'catalog:product_list' %}">Все объявления</a></h5>
                </div>
                <div class="card-body">
                    <div class="card-title">
                        {% include 'catalog/includes/inc_search_field.html' %}
                    </div>
                    {% for obj in page_obj %}
                    <ul>
                        <li>
                            <ul class="list-inline">
                                <li class="list-inline-item"
                                    style="font-family: cursive; font-weight: 600; font-size: 100%">
                                    <a href="{% url 'catalog:product_detail' obj.pk %}">{{obj.name}}</a>
                                </li>
                                <li class="list-inline-item">{{obj.published|date:"d.m.Y H:i:s"}}</li>
                            </ul>
                            {{obj.description}}
                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    Цена: {{obj.price}} рублей
                                </li>
                                {% if user.is_authenticated %}
                                {% if user != obj.user_product %}
                                <li class="list-inline-item">
                                    <button type="button" class="btn btn-outline-dark"
                                            style="font-size: 10px;">
                                        В корзину
                                    </button>
                                </li>
                                {% else %}
                                {% endif %}
                                {% else %}
                                {% endif %}
                            </ul>
                            <strong>Пользователь: </strong>{{ obj.user_product|default:"нет" }}
                            <ul class="list-inline">
                            {% for version in versions %}
                                {% if version.product.pk == obj.pk %}
                                <li class="list-inline-item">
                                    <strong>Название: </strong>{{ version.title|lower }},
                                </li>
                                <li class="list-inline-item">
                                    <strong>номер: </strong>{{ version.number }},
                                </li>
                                <li class="list-inline-item">
                                    <strong>статус: </strong> активно.
                                </li>
                                {% endif %}
                            {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    {% endfor %}

                    {% include 'catalog/includes/inc_paginate.html' %}

                </div>
                {% if user.is_authenticated %}
                <div class="card-footer">
                        <a href="{% url 'catalog:add_product' %}" class="btn btn-primary">Добавить товар</a>
                </div>
                {% else %}
                {% endif %}
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Категории товаров</h5>
                </div>
                <div class="card-body">
                    {% for cat in categories %}
                    <ul>
                        <li>
                            <div class="btn-group">
                                <button type="button" class="btn btn-secondary dropdown-toggle"
                                        data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                    <span>{{cat.category}}</span>
                                </button>
                                {% if user.is_staff %}
                                <a href="{% url 'catalog:update_category' cat.pk %}"
                                   class="btn btn-outline-primary">
                                    Изменить
                                </a>
                                {% if perms.catalog.delete_category %}
                                <a href="{% url 'catalog:delete_category' cat.pk %}"
                                   class="btn btn-outline-danger float-right">
                                    Удалить
                                </a>
                                {% endif %}
                                {% endif %}
                                <ul class="dropdown-menu">
                                    {% if cat.categories.all %}
                                    {% for prod in cat.categories.all %}
                                    <li><a class="dropdown-item"
                                           href="{% url 'catalog:product_detail' prod.pk %}">{{prod.name}}</a>
                                    </li>
                                    {% endfor %}
                                    {% else %}
                                    <li><a class="dropdown-item">Нет товаров</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </li>
                    </ul>
                    {% endfor %}
                </div>
                {% if perms.catalog.add_category %}
                <div class="card-footer">
                    <a href="{% url 'catalog:add_category' %}" class="btn btn-primary">Добавить категорию</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

board_service/catalog/templates/catalog/products_by_keyword.html
{% extends "layout/basic.html" %}
{% load products_tags %}


{% block content %}
<div class="card-body">
    <div class="card-title">
        <h5 class="card-title"><a href="{% url 'catalog:product_list' %}">Все объявления</a></h5>
    </div>
    {% if keyword|product_by_keyword %}
    {% for item in keyword|product_by_keyword %}
    <ul>
        <li>
            <ul class="list-inline">
                <li class="list-inline-item"
                    style="font-family: cursive; font-weight: 600; font-size: 100%">
                    <a href="{% url 'catalog:product_detail' item.pk %}">{{item.name}}</a>
                </li>
                <li class="list-inline-item">{{item.published|date:"d.m.Y H:i:s"}}</li>
            </ul>
            {{item.description}}
            <ul class="list-inline">
                <li class="list-inline-item">
                    Цена: {{item.price}} рублей
                </li>
                {% if user.is_authenticated %}
                {% if user == item.user_product %}
                <li class="list-inline-item">
                    <button type="button" class="btn btn-outline-dark"
                            style="font-size: 10px;">
                        В корзину
                    </button>
                </li>
                {% else %}
                {% endif %}
                {% else %}
                {% endif %}
            </ul>
        </li>
    </ul>
    {% endfor %}
    {% else %}
    <b>Продукт не найден</b>
    {% endif %}
</div>

{% endblock %}